### ISSUE TITLE
Boucle principale

### ISSUE THREAD

**Issue by agingrasc** [agingrasc/PathfinderPhorum#4]
- [x] Draft de la séquence initiale
- [x] Implémentation séquence de combat à durée fixe

**Comment by david2194** [comment]
- [ ] Draft de la séquence initiale
- [ ] Implémentation séquence de combat à durée fixe

**Comment by david2194** [comment]
La séquence de combat à durée fixe est, pour le moment, une séquence de combat qui se termine lorsqu'un des deux participants tombe à 0 hp (ou moins). Todos :
- Ajouter des valeurs aléatoires pour les dégats et +hit
- Déterminer la nomenclature à utiliser, puisque les concepts font partie du core du projet
